name       : fcitx-configtool
version    : 0.4.10
release    : 2
source     :
    - https://download.fcitx-im.org/fcitx-configtool/fcitx-configtool-0.4.10.tar.xz : bcc4976976bfbddbfec3f689f38927fbabc7f7fa611ea252a789583ea14cd1fb
license    : GPL-2.0-or-later
component  : desktop.core
summary    : GTK based config tool for Fcitx
description: |
    GTK based config tool for Fcitx
builddeps  :
    - pkgconfig(fcitx)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(iso-codes)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/fcitx-configtool.desktop $installdir/usr/share/applications/fcitx-configtool.desktop
